FROM node as build-stage
COPY . /app
WORKDIR /app
RUN npm install && \
    npm install --save buefy buefy/dist/buefy.css firebase && \
    npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
