apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: DATABASE_HOSTNAME
          value: mongo
        - name: DATABASE_NAME
          value: ms_restaurants
        - name: DATABASE_PASSWORD
          value: "123456"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_USERNAME
          value: root
        image: backend
        name: backend
        ports:
        - containerPort: 8081
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
