apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-restaurants
  name: ms-restaurants
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-restaurants
    spec:
      containers:
      - image: ms-restaurants-frontend
        name: ms-restaurants-frontend
        ports:
        - containerPort: 80
      - image: ms-restaurants-backend
        name: ms-restaurants-backend
        ports:
        - containerPort: 8080
        - containerPort: 50051
      - image: mongo
        name: ms-restaurants-db
        volumeMounts:
          - mountPath: /data/db
            name: db
            subPath: restaurants-db-v1
      restartPolicy: Always
      volumes:
        - name: db
          gcePersistentDisk:
            pdName: ms-restaurants
            fsType: ext4
status: {}
