apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    app: backend
status:
  loadBalancer: {}
